import { useState, useEffect } from "react";
import jsPDF from "jspdf";

const TABS = [
  { id: "summary", label: "📋 Summary", emoji: "📋" },
  { id: "notes", label: "📖 Notes", emoji: "📖" },
  { id: "questions", label: "❓ Questions", emoji: "❓" },
  { id: "saved", label: "💾 Saved Notes", emoji: "💾" },
];

function formatText(text) {
  if (!text || text.trim() === "") {
    return `<p style="color:#94a3b8;font-style:italic">Koi content nahi mila. Dobara generate karo.</p>`;
  }
  return text
    .replace(/^## (.+)$/gm, '<h2 class="note-h2">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 class="note-h3">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^\• (.+)$/gm, "<li>$1</li>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>[\s\S]+?<\/li>)(\n(?!<li>))/g, "<ul>$1</ul>$2")
    .replace(/\n{2,}/g, "</p><p>")
    .replace(/\n/g, "<br/>");
}

export default function NotesDisplay({ notes, fileName }) {
  const [active, setActive] = useState("summary");
  const [savedNotes, setSavedNotes] = useState([]);
  const [saveStatus, setSaveStatus] = useState("");

  useEffect(() => {
    const stored = JSON.parse(localStorage.getItem("pdfexplainer_notes") || "[]");
    setSavedNotes(stored);
  }, []);

  const currentContent = notes[active] || "";

  function handleSave() {
    const existing = JSON.parse(localStorage.getItem("pdfexplainer_notes") || "[]");
    const entry = {
      id: Date.now(),
      fileName: fileName || "Untitled",
      date: new Date().toLocaleDateString("en-IN"),
      summary: notes.summary,
      notes: notes.notes,
      questions: notes.questions,
    };
    const updated = [entry, ...existing].slice(0, 20); // max 20 saved
    localStorage.setItem("pdfexplainer_notes", JSON.stringify(updated));
    setSavedNotes(updated);
    setSaveStatus("✅ Saved!");
    setTimeout(() => setSaveStatus(""), 2000);
  }

  function handleDeleteSaved(id) {
    const updated = savedNotes.filter((n) => n.id !== id);
    localStorage.setItem("pdfexplainer_notes", JSON.stringify(updated));
    setSavedNotes(updated);
  }

  function handleLoadSaved(entry) {
    // Load into current notes by dispatching a custom event
    window.dispatchEvent(new CustomEvent("loadSavedNote", { detail: entry }));
    setActive("summary");
  }

  function exportPDF() {
    const doc = new jsPDF({ orientation: "p", unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 15;
    const maxW = pageW - margin * 2;

    // Header
    doc.setFillColor(124, 58, 237);
    doc.rect(0, 0, pageW, 20, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("PDF Explainer — NIOS Study Notes", margin, 13);

    doc.setTextColor(40, 40, 40);
    let y = 28;

    function addSection(title, content) {
      if (!content || content.trim() === "") return;
      // Section heading
      doc.setFillColor(237, 233, 254);
      doc.rect(margin - 2, y - 5, maxW + 4, 10, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(109, 40, 217);
      doc.text(title, margin, y + 1);
      y += 10;
      doc.setTextColor(40, 40, 40);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);

      // Strip markdown
      const clean = content
        .replace(/#{1,3} (.+)/g, "\n$1\n")
        .replace(/\*\*(.+?)\*\*/g, "$1")
        .replace(/^\• /gm, "• ")
        .replace(/^- /gm, "• ");

      const lines = doc.splitTextToSize(clean, maxW);
      for (const line of lines) {
        if (y > 275) { doc.addPage(); y = 20; }
        doc.text(line, margin, y);
        y += 5.5;
      }
      y += 6;
    }

    addSection("📋 Summary", notes.summary);
    addSection("📖 Detailed Notes", notes.notes);
    addSection("❓ Practice Questions", notes.questions);

    // Footer
    const pages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`${fileName || "Notes"} • Generated by PDF Explainer • Page ${i}/${pages}`, margin, 292);
    }

    doc.save(`${(fileName || "notes").replace(".pdf", "")}_study_notes.pdf`);
  }

  return (
    <div className="notes-wrapper">
      {/* Banner */}
      <div className="study-banner">
        <img
          src="https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=900&q=80"
          alt="Study"
        />
        <div className="banner-overlay">
          <span>📚 AI-Generated Study Notes</span>
          <small>{fileName || "NIOS Class 12"}</small>
        </div>
      </div>

      {/* Action bar */}
      <div className="action-bar">
        <button className="action-btn save-btn" onClick={handleSave}>
          💾 {saveStatus || "Save Notes"}
        </button>
        <button className="action-btn pdf-btn" onClick={exportPDF}>
          📥 Download PDF
        </button>
        <button
          className="action-btn copy-btn"
          onClick={() => {
            navigator.clipboard.writeText(currentContent);
            alert("Copied!");
          }}
        >
          📋 Copy
        </button>
      </div>

      {/* Tabs */}
      <div className="tabs">
        {TABS.map((t) => (
          <button
            key={t.id}
            className={`tab ${active === t.id ? "active" : ""}`}
            onClick={() => setActive(t.id)}
          >
            {t.label}
            {t.id === "saved" && savedNotes.length > 0 && (
              <span className="badge">{savedNotes.length}</span>
            )}
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="notes-content">
        {active === "saved" ? (
          <div className="saved-list">
            {savedNotes.length === 0 ? (
              <p className="empty-msg">Koi saved notes nahi hain abhi. Pehle save karo! 💾</p>
            ) : (
              savedNotes.map((entry) => (
                <div key={entry.id} className="saved-card">
                  <div className="saved-info">
                    <span className="saved-name">📄 {entry.fileName}</span>
                    <span className="saved-date">{entry.date}</span>
                  </div>
                  <div className="saved-actions">
                    <button onClick={() => handleLoadSaved(entry)} className="load-btn">
                      📂 Load
                    </button>
                    <button onClick={() => handleDeleteSaved(entry.id)} className="del-btn">
                      🗑️ Delete
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        ) : (
          <div
            className="notes-body"
            dangerouslySetInnerHTML={{ __html: formatText(currentContent) }}
          />
        )}
      </div>
    </div>
  );
}